micronaut:
  application:
    name: pixRest

grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    keymanager:
      address: 'localhost:50051'
      plaintext: true
      max-retry-attempts: 10


jackson:
  serialization:
    writeDatesAsTimestamps: false


#micronaut:
#  http:
#    client:
#      read-timeout: 15s
#      connect-timeout: 10s
#    read-idle-timeout: 5m